version: '3.7'
services:
  node:
    image: node:16-alpine
    volumes:
      - ./src:/workspace
    tty: true
    working_dir: /workspace

  mongodb:
    image: "mongo-master"
    build: ./mongo-master    
    volumes:
      - ./data/master:/data/db  
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128    
    volumes:
      - ./data/mongo-rs0-2:/data/db

  mongo-rs0-3:
    image: "mongo"
    command: --replSet rs0 --oplogSize 128    
    volumes:
      - ./data/mongo-rs0-3:/data/db

  setup-rs:
    image: "setup-rs"
    build: ./setup
    depends_on:
      - "mongodb"
    command: tail -f /dev/null
    # mongo mongodb://mongodb:27017 replicaSet.js
    
  

